# Generated by Django 4.0.4 on 2022-06-16 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='relationship',
            field=models.IntegerField(choices=[(0, 'Na'), (1, 'Single'), (2, 'In A Relationship'), (3, 'Married'), (4, 'Engaged')], default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='work',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
