# Generated by Django 4.0.4 on 2022-06-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile_first_name_profile_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='relationship',
            field=models.IntegerField(choices=[(0, 'Na'), (1, 'Single'), (2, 'In A Relationship'), (3, 'Married'), (4, 'Engaged')], default=0),
        ),
    ]
